// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKfMDTsLWjf8YqaR6x2RyBfjo05Q6yOwc',
    appId: '1:726435208417:web:21414814039a0ab8f9aba0',
    messagingSenderId: '726435208417',
    projectId: 'testgih-d7512',
    authDomain: 'testgih-d7512.firebaseapp.com',
    storageBucket: 'testgih-d7512.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Nn8owaW1y2os96imWLe0sn-2lFM2jDQ',
    appId: '1:726435208417:android:5c5481a9b7d08006f9aba0',
    messagingSenderId: '726435208417',
    projectId: 'testgih-d7512',
    storageBucket: 'testgih-d7512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXhcZVg-mxmr4GIsrdz1NO0PxGNRp7tYI',
    appId: '1:726435208417:ios:4c3a20179500212ef9aba0',
    messagingSenderId: '726435208417',
    projectId: 'testgih-d7512',
    storageBucket: 'testgih-d7512.appspot.com',
    iosBundleId: 'com.example.testgih',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKfMDTsLWjf8YqaR6x2RyBfjo05Q6yOwc',
    appId: '1:726435208417:web:f1b88538798c93c4f9aba0',
    messagingSenderId: '726435208417',
    projectId: 'testgih-d7512',
    authDomain: 'testgih-d7512.firebaseapp.com',
    storageBucket: 'testgih-d7512.appspot.com',
  );
}
